name: learnflow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 📊 Chart
  fl_chart: ^0.68.0

  # 🔥 Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.2

  # 🌐 HTTP
  http: ^1.2.0

  # 💾 Local cache
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 🔔 Local Notifications
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/LeranFlow_logo.png
    - assets/images/Img_Onboarding.webp
    - assets/images/Img_Onboarding2.webp
    - assets/images/Img_Onboarding3.webp
    - assets/images/math.png
    - assets/images/Eng.png
    - assets/images/dev1.png
    - assets/images/dev2.png
    - assets/images/Social_Studies.png
    - assets/images/Programming.png
